case 'fcose':
      return {
        name: 'fcose',
        quality: 'default',
        randomize: true,
        animate: false,
        fit: true,
        padding: 30,
        nodeDimensionsIncludeLabels: true,
        packComponents: false,
        nodeSeparation: 150,
        componentSpacing: 200,
        idealEdgeLength: 100,
        edgeElasticity: 0.45,
        nodeRepulsion: 4500,
        gravity: 0.25,
        gravityRangeCompound: 1.5,
        gravityCompound: 1.0,
      };